=== maisiukartyom/VT_Lab3/src/main/resources/archive_db.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="archive_db">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="students">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="student" maxOccurs="unbounded" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:all>
                                        <xsd:element type="xsd:string" name="name"/>
                                        <xsd:element type="xsd:string" name="surname"/>
                                        <xsd:element type="xsd:string" name="university"/>
                                        <xsd:element type="xsd:string" name="speciality"/>
                                        <xsd:element type="xsd:short" name="cource_number"/>
                                        <xsd:element type="xsd:double" name="average_score"/>
                                    </xsd:all>
                                    <xsd:attribute type="xsd:ID" name="id" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== maisiukartyom/VT_Lab3/src/main/resources/archive_db.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<archive_db xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="archive_db.xsd">

    <students>
        <student id="s0">
            <name>Pasha</name>
            <surname>Vashkevich</surname>
            <university>BSUIR</university>
            <speciality>POIT</speciality>
            <cource_number>3</cource_number>
            <average_score>5.0</average_score>
        </student>
        <student id="s1">
            <name>Dzmitry</name>
            <surname>Susha</surname>
            <university>BSUIR</university>
            <speciality>POIT</speciality>
            <cource_number>3</cource_number>
            <average_score>10.0</average_score>
        </student>
        <student id="s2">
            <name>Nastya</name>
            <surname>Abakanovich</surname>
            <university>BSUIR</university>
            <speciality>POIT</speciality>
            <cource_number>3</cource_number>
            <average_score>8.0</average_score>
        </student>
    </students>

</archive_db>
